name: Build Headscale

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: juanfont/headscale
        ref: main

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.24'

    - name: Verify Go version
      run: go version

    - uses: cachix/install-nix-action@v20
  
    
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y make
        sudo apt-get install protobuf-compiler -y
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest
        go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest
        sudo wget -O /usr/bin/buf "https://github.com/bufbuild/buf/releases/download/v1.52.0/buf-$(uname -s)-$(uname -m)"
        sudo chmod +x /usr/bin/buf

    - name: Build
      run: |
        export PATH="$PATH:$(go env GOPATH)/bin"
        nix develop
        make generate
        nix develop --command -- go build -o "headscale" ./cmd/headscale
    - uses: actions/upload-artifact@v4
      with:
        name: headscale
        path: ./headscale