name: Build Headscale

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: juanfont/headscale
        ref: main

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.24'

    - name: Verify Go version
      run: go version

    - name: Install Nix
      run: |
        sh <(curl -L https://nixos.org/nix/install) --daemon
        . $HOME/.nix-profile/etc/profile.d/nix.sh
        nix-channel --update
    
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y make

    - name: Build
      run: |
       . $HOME/.nix-profile/etc/profile.d/nix.sh 
        make build

    - name: Test 
      run: |
        make test

    - name: Save build artifact
      uses: actions/upload-artifact@v3
      with:
          name: headscale-build
          path: ./README.txt