name: Build Headscale

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: juanfont/headscale
        ref: main

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.24'

    - name: Verify Go version
      run: go version

    - uses: cachix/install-nix-action@v20
  
    
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y make
        sudo wget -o /usr/bin/buf "https://github.com/bufbuild/buf/releases/download/v1.52.0/buf-$(uname -s)-$(uname -m)"
        sudo chmod +x /usr/bin/buf

    - name: Build
      run: |
        nix develop
        make generate
        make build
        ls
        tar -zcvf /tmp/dist.tar.gz ./

  
    - uses: actions/upload-artifact@v4
      with:
        name: my-dist
        path: /tmp/dist.tar.gz