name: Build Headscale

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: headscale/headscale
        ref: main

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Verify Go version
      run: go version

    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y make

    - name: Build
      run: |
        make build

    - name: Test 
      run: |
        make test
