name: Build Headscale

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: juanfont/headscale
        ref: main

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.24'

    - name: Verify Go version
      run: go version

    - uses: cachix/install-nix-action@v20
  
    
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y make

    - name: Build
      run: |
        make build

    - name: Test 
      run: |
        make test
    
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: ./README.txt